"""empty message

Revision ID: 33251e5c7f7b
Revises: 847eb5a0d5ea
Create Date: 2023-03-09 21:23:44.699880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33251e5c7f7b'
down_revision = '847eb5a0d5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
