"""empty message

Revision ID: 847eb5a0d5ea
Revises: 760c97bf25bc
Create Date: 2023-03-07 20:54:05.478956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847eb5a0d5ea'
down_revision = '760c97bf25bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
